<?xml version="1.0" encoding="UTF-8"?>
<xsl:transform version="1.1" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jaxws="https://jakarta.ee/xml/ns/jaxws">
<!-- JAX xsl:transform version="1.1" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jaxws="http://java.sun.com/xml/ns/jaxws" -->
<xsl:output method="text" />
<xsl:strip-space elements="*" />
<xsl:template match="/">
  <xsl:for-each select="wsdl:definitions/wsdl:portType[@*]">
   /* GENERATED by XSLT */ String[] <xsl:value-of select="@name" />Operations = {
   <xsl:for-each select="wsdl:operation[@*]"> "<xsl:value-of select="@name" />", 
   </xsl:for-each> };
  </xsl:for-each>
</xsl:template>
</xsl:transform>
