#!/bin/sh

MVNREPO="$1"
PROJDIR="$2"

JAVA=/usr/lib/jvm/java-11-openjdk-amd64/bin/java


JAVA_CPATH=${MVNREPO}/repository/org/jvnet/mimepull/mimepull/1.9.15/mimepull-1.9.15.jar:${MVNREPO}/repository/com/fasterxml/woodstox/woodstox-core/6.2.6/woodstox-core-6.2.6.jar:${MVNREPO}/repository/com/sun/activation/jakarta.activation/2.0.1/jakarta.activation-2.0.1.jar:${MVNREPO}/repository/com/sun/mail/jakarta.mail/2.0.1/jakarta.mail-2.0.1.jar:${MVNREPO}/repository/jakarta/xml/ws/jakarta.xml.ws-api/3.0.1/jakarta.xml.ws-api-3.0.1.jar:${MVNREPO}/repository/com/sun/xml/bind/jaxb-xjc/3.0.2/jaxb-xjc-3.0.2.jar:${MVNREPO}/repository/jakarta/annotation/jakarta.annotation-api/2.0.0/jakarta.annotation-api-2.0.0.jar:${MVNREPO}/repository/jakarta/jws/jakarta.jws-api/3.0.0/jakarta.jws-api-3.0.0.jar:${MVNREPO}/repository/org/glassfish/ha/ha-api/3.1.13/ha-api-3.1.13.jar:${MVNREPO}/repository/org/glassfish/gmbal/gmbal-api-only/4.0.3/gmbal-api-only-4.0.3.jar:${MVNREPO}/repository/com/sun/xml/messaging/saaj/saaj-impl/2.0.1/saaj-impl-2.0.1.jar:${MVNREPO}/repository/org/codehaus/woodstox/stax2-api/4.2.1/stax2-api-4.2.1.jar:${MVNREPO}/repository/com/sun/xml/ws/jaxws-tools/3.0.2/jaxws-tools-3.0.2.jar:${MVNREPO}/repository/org/jvnet/staxex/stax-ex/2.0.1/stax-ex-2.0.1.jar:${MVNREPO}/repository/com/sun/xml/bind/jaxb-jxc/3.0.2/jaxb-jxc-3.0.2.jar:${MVNREPO}/repository/org/glassfish/external/management-api/3.2.3/management-api-3.2.3.jar:${MVNREPO}/repository/jakarta/xml/soap/jakarta.xml.soap-api/2.0.1/jakarta.xml.soap-api-2.0.1.jar:${MVNREPO}/repository/com/sun/xml/ws/jaxws-rt/3.0.2/jaxws-rt-3.0.2.jar:${MVNREPO}/repository/com/sun/xml/fastinfoset/FastInfoset/2.0.0/FastInfoset-2.0.0.jar:${MVNREPO}/repository/com/sun/xml/bind/jaxb-impl/3.0.2/jaxb-impl-3.0.2.jar:${MVNREPO}/repository/jakarta/xml/bind/jakarta.xml.bind-api/3.0.1/jakarta.xml.bind-api-3.0.1.jar:${MVNREPO}/repository/onvif-relay/onvif-naming-jaxb-tools/3.0.2/onvif-naming-jaxb-tools-3.0.2.jar:${MVNREPO}/repository/com/sun/xml/bind/jaxb-core/3.0.2/jaxb-core-3.0.2.jar:${MVNREPO}/repository/com/sun/xml/stream/buffer/streambuffer/2.0.2/streambuffer-2.0.2.jar:${MVNREPO}/repository/com/sun/xml/ws/jaxws-maven-plugin/3.0.2/jaxws-maven-plugin-3.0.2.jar

MAIN_JAR=${MVNREPO}/repository/onvif-relay/onvif-naming-jaxb-tools/3.0.2/onvif-naming-jaxb-tools-3.0.2.jar

cd ${PROJDIR} && ${JAVA} '-cp' ${MAIN_JAR}:${JAVA_CPATH} 'com.sun.tools.ws.WsImport' '-keep' '-s' ${PROJDIR}/target/generated-sources/wsimport '-d' ${PROJDIR}/target/classes '-extension' '-Xnocompile' '-wsdllocation' '/META-INF/wsdl/www.onvif.org/ver10/onvif_device.wsdl' file:${PROJDIR}/src/main/resources/META-INF/wsdl/www.onvif.org/ver10/onvif_device.wsdl
